appname = check
serverid = 1000

httpport = 7003
runmode = dev

#开启热更新
Graceful = true

#开启JSON请求
copyrequestbody = true

include ./lat_long.conf
GroupInterval = 4500,9999

[Redis]
IdleCount=1024
Servers="webface02.4aj77i.ng.0001.apse1.cache.amazonaws.com:6379"
Password=""

[Mgo]
#Query="replicaSet=experiential-shard-0&authSource=admin"
Url="ykmongo.cluster-cclfxubxjboe.ap-southeast-1.docdb.amazonaws.com:27017"
User="root"
Password="FFiY3Gtu"
PoolNum=64
##Ssl=false

[Nats]
Timeout=1
User="minigame"
Password="M123G321"
Servers="nats://10.0.6.211:4222"
