appname = message
serverid = 1000
#监听端口
httpport = 8010
runmode = dev

#开启热更新
Graceful = true

#开启JSON请求
copyrequestbody = true
GroupTaskAccountNum=10

[Redis]
IdleCount=1024
Servers="webface02.4aj77i.ng.0001.apse1.cache.amazonaws.com:6379"
Password=""

[Mgo]
Url="ykmongo.cluster-cclfxubxjboe.ap-southeast-1.docdb.amazonaws.com:27017"
User="root"
Password="FFiY3Gtu"
PoolNum=64



